# Preload the wallpaper(s)
preload = /path/to/wallpaper.png
# If you have more than one, use multiple preload lines
# preload = /path/to/wallpaper2.png

# Set the wallpaper for the specified monitor
wallpaper = MonitorName,/path/to/wallpaper.png
# For all monitors, use:
# wallpaper = ,/path/to/wallpaper.png

ipc = on
